version: "3"
services:
  database:
    image: postgres:11-alpine
    environment:
      - POSTGRES_DB=devnews
      - POSTGRES_USER=dev_user
      - POSTGRES_PASSWORD=dev_pass
    ports:
      - "5433:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
volumes:
  db-data: