package se.sda.backend.devNews.Article;

import javax.persistence.*;

// to make a class into database, using Entity and assign Id annotation will do.
@Entity
@Table(name = "Posts") // explicitly define the database name, otherwise same as the class name.
// By explicitly give the table/column names, the database is independent of the code, though may cause confusion.
public class Article {
    @Id
    // the id will be automatically generated by database.
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;


    private String title;
    // by columnDefiniation to TEXT, not limite to char 255 as in Java,
    // name = "Post", change this column name in database to Post, by default this column is same as the varible.
    @Column(columnDefinition = "TEXT", name="Post")
    private String body;
    private String author;

    public Article() { }

    public Article(Long id, String title, String body, String author) {
        this.id = id;
        this.title = title;
        this.body = body;
        this.author = author;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getBody() {
        return body;
    }

    public void setBody(String body) {
        this.body = body;
    }

    public String getAuthor() {
        return author;
    }

    public void setAuthor(String author) {
        this.author = author;
    }
}
